require("configs.visual.plugins_setup.gitsigns")
require("configs.visual.plugins_setup.colorscheme")
require("configs.visual.plugins_setup.lualine")
require("configs.visual.plugins_setup.oil")
require("configs.visual.plugins_setup.snacksc")

local function plugins()
	-- Colorscheme("gruber-darker")
	Colorscheme("rose-pine")
	Gitsigns()
	Lualine()
	Oil()
	Snacksc()
end
plugins()

require("configs.visual.extras.pattern_highlight")
require("configs.visual.extras.complementary_highlights")
require("configs.visual.extras.code_folding")
require("configs.visual.extras.diagnostics")
require("configs.visual.extras.search_and_yank")
require("configs.visual.extras.line")

local function extras()
	Pattern_Highlight()
	-- Complementary_Highlights("gruber-darker")
	Complementary_Highlights("rose-pine")
	Code_Folding()
	Diagnostics()
	Search_And_Yank()
	Line()
end
extras()
