require("marin.editor_configs.appearance.code_folding")
require("marin.editor_configs.appearance.colorscheme")
require("marin.editor_configs.appearance.diagnostics")
require("marin.editor_configs.appearance.highlight")
require("marin.editor_configs.appearance.line")
require("marin.editor_configs.appearance.line_number")
require("marin.editor_configs.appearance.search_casing")

function Appearance()
	CodeFolding()
	Colorscheme()
	Diagnostics()
	Highlight()
	Line()
	LineNumber()
	SearchCasing()
end
