general.import = [
    "~/.config/alacritty/themes/default.toml"
]

[font]
size = 17
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }

[keyboard]
bindings = [{ key="F11", action="ToggleFullscreen" },]

[env]
term = "xterm-256color"

[window]
padding = { x = 10, y = 0 }
dynamic_padding = true
decorations="None"
